version: '3.8'

services:
  flask:
    container_name: flask_api
    image: python:3.9.21-alpine3.21
    working_dir: /app
    command: ["/bin/sh", "-c", "pip install --upgrade pip && pip install -r requirements.txt && python app.py"]

    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

networks:
  default:
    driver: bridge

